import { useState, useCallback, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { TrendingUp, TrendingDown, DollarSign, Download, Sparkles, Loader2, Check, Database, Copy, CheckCheck, Plane, Target, BarChart3, AlertTriangle, Heart } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, ResponsiveContainer, Tooltip } from 'recharts';
import { toast } from 'sonner';
import {
  FinancialAnalysis,
  ProcessingProgress,
  sanitizeFinancialData,
} from '../lib/dna-processor';
import { formatCurrency } from '../lib/simulator-engine';
import { saveAnalysisSnapshot } from '../lib/api';
import { MotionCard, MotionButton } from '../components/ui/MotionCard';
import { SequencingLoader } from '../components/ui/Skeleton';
import { useAppStore } from '../lib/store';
import { useFirstSnapshotCelebration } from '../components/ui/SuccessConfetti';
import { performAnalysis, type AnalysisType, type AIContext } from '../lib/services/AIService';
import SmartUpload from '../components/ui/SmartUpload';
import type { ExtractedFinancials } from '../lib/universal-parser';
import { GradeBadge } from '../components/design-system';
import { cn } from '../lib/utils';

const DEFAULT_CASH = 1200000;

const DEFAULT_ANALYSIS: FinancialAnalysis = sanitizeFinancialData({
  monthlyBurn: 60000,
  monthlyRevenue: 85000,
  cashOnHand: DEFAULT_CASH,
  revenueGrowth: 0.18,
  expenseGrowth: 0.03,
  revenueTrend: [
    { month: 'Jul', revenue: 45000, expenses: 52000 },
    { month: 'Aug', revenue: 52000, expenses: 54000 },
    { month: 'Sep', revenue: 61000, expenses: 55000 },
    { month: 'Oct', revenue: 58000, expenses: 57000 },
    { month: 'Nov', revenue: 72000, expenses: 58000 },
    { month: 'Dec', revenue: 85000, expenses: 60000 },
  ],
});

const DEMO_ANALYSIS: FinancialAnalysis = sanitizeFinancialData({
  monthlyBurn: 850000,
  monthlyRevenue: 2400000,
  cashOnHand: 18000000,
  revenueGrowth: 0.28,
  expenseGrowth: 0.12,
  revenueTrend: [
    { month: 'Jul', revenue: 1100000, expenses: 580000 },
    { month: 'Aug', revenue: 1350000, expenses: 620000 },
    { month: 'Sep', revenue: 1680000, expenses: 650000 },
    { month: 'Oct', revenue: 1950000, expenses: 720000 },
    { month: 'Nov', revenue: 2150000, expenses: 780000 },
    { month: 'Dec', revenue: 2400000, expenses: 850000 },
  ],
});

const cardVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.05, duration: 0.4, ease: 'easeOut' },
  }),
};

const CustomTooltip = ({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; dataKey: string }>; label?: string }) => {
  if (!active || !payload) return null;
  return (
    <div className="glass-card p-3 border border-white/20">
      <p className="text-gray-400 text-xs mb-2">{label}</p>
      {payload.map((entry, i) => (
        <p key={i} className={`text-sm font-semibold ${entry.dataKey === 'revenue' ? 'text-cyan-electric' : 'text-violet-vivid'}`}>
          {entry.dataKey === 'revenue' ? 'Revenue' : 'Expenses'}: {formatCurrency(entry.value, true)}
        </p>
      ))}
    </div>
  );
};

function generateInvestorReport(analysis: FinancialAnalysis): string {
  const netBurn = analysis.monthlyBurn - analysis.monthlyRevenue;
  const report = `
RUNWAY DNA - INVESTOR REPORT
Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

EXECUTIVE SUMMARY
-----------------
Financial Grade: ${analysis.grade} (${analysis.gradeLabel})
Runway: ${analysis.runwayMonths >= 999 ? 'Infinite (Profitable)' : `${analysis.runwayMonths.toFixed(1)} months`}

KEY METRICS
-----------
Monthly Revenue:      ${formatCurrency(analysis.monthlyRevenue)}
Monthly Burn:         ${formatCurrency(analysis.monthlyBurn)}
Net Burn Rate:        ${netBurn > 0 ? '-' : '+'}${formatCurrency(Math.abs(netBurn))}
Cash on Hand:         ${formatCurrency(analysis.cashOnHand)}

GROWTH INDICATORS
-----------------
Revenue Growth:       ${(analysis.revenueGrowth * 100).toFixed(1)}% MoM
Expense Growth:       ${(analysis.expenseGrowth * 100).toFixed(1)}% MoM
Profit Margin:        ${analysis.profitMargin.toFixed(1)}%
Burn Multiple:        ${analysis.burnMultiple > 10 ? '>10x' : `${analysis.burnMultiple.toFixed(1)}x`}

TREND DATA (Last 6 Months)
--------------------------
${analysis.revenueTrend.map(t => `${t.month}: Revenue ${formatCurrency(t.revenue)} | Expenses ${formatCurrency(t.expenses)}`).join('\n')}

AI INSIGHT
----------
${analysis.insight}

---
Report generated by Runway DNA
  `.trim();
  return report;
}

export default function DNALab() {
  const location = useLocation();
  const { setCurrentAnalysis } = useAppStore();
  const [analysis, setAnalysis] = useState<FinancialAnalysis>(DEFAULT_ANALYSIS);
  const [progress, setProgress] = useState<ProcessingProgress | null>(null);
  const [cashInput, setCashInput] = useState(DEFAULT_CASH);
  const [syncStatus, setSyncStatus] = useState<'idle' | 'syncing' | 'synced' | 'error'>('idle');
  const [showSuccessPulse, setShowSuccessPulse] = useState(false);
  const [copied, setCopied] = useState(false);

  const [isAnalysisRunning, setIsAnalysisRunning] = useState(false);
  const [activeAnalysisMode, setActiveAnalysisMode] = useState<AnalysisType | null>(null);
  const [analysisResult, setAnalysisResult] = useState<string | null>(null);
  const [uploadMode] = useState<'basic' | 'smart'>('smart'); // Default to smart mode

  // Confetti celebration for first snapshot save
  const { celebrateFirstSnapshot, ConfettiComponent } = useFirstSnapshotCelebration();

  useEffect(() => {
    setCurrentAnalysis(analysis);
  }, [analysis, setCurrentAnalysis]);

  // Handle Demo Mode
  useEffect(() => {
    const searchParams = new URLSearchParams(location.search);
    if (searchParams.get('demo') === 'true') {
      setAnalysis(DEMO_ANALYSIS);
      setCashInput(DEMO_ANALYSIS.cashOnHand);
      toast.success('Demo Mode Active', { description: 'Loaded unicorn dataset for showcase.' });
    }
  }, [location.search]);

  // Handler for AI-extracted financial data from SmartUpload
  const handleAIExtracted = useCallback(async (data: ExtractedFinancials, confidence: number) => {
    // Convert AI-extracted data to FinancialAnalysis format
    const newAnalysis = sanitizeFinancialData({
      monthlyBurn: data.monthlyBurn,
      monthlyRevenue: data.monthlyRevenue,
      cashOnHand: data.cashOnHand,
      revenueGrowth: data.revenueGrowth,
      expenseGrowth: data.expenseGrowth,
      revenueTrend: data.revenueTrend || analysis.revenueTrend,
    });

    setAnalysis(newAnalysis);
    setCashInput(data.cashOnHand);
    setShowSuccessPulse(true);
    setTimeout(() => setShowSuccessPulse(false), 600);

    toast.success('AI Extraction Complete', {
      description: `Confidence: ${Math.round(confidence * 100)}% • Grade ${newAnalysis.grade} • ${newAnalysis.runwayMonths.toFixed(1)} months runway`,
    });

    // Save to archive
    setSyncStatus('syncing');
    const saveResponse = await saveAnalysisSnapshot(newAnalysis);
    if (saveResponse.error) {
      setSyncStatus('error');
    } else {
      setSyncStatus('synced');
      celebrateFirstSnapshot();
    }
    setTimeout(() => setSyncStatus('idle'), 3000);
  }, [analysis.revenueTrend, celebrateFirstSnapshot]);

  // Quick Analysis handler
  const runAnalysis = useCallback(async (mode: AnalysisType) => {
    if (isAnalysisRunning) return;

    setIsAnalysisRunning(true);
    setActiveAnalysisMode(mode);
    setAnalysisResult(null);

    try {
      // Build AI context from current analysis
      const context: AIContext = {
        analysis: analysis,
        cashOnHand: analysis.cashOnHand,
        monthlyBurn: analysis.monthlyBurn,
        monthlyRevenue: analysis.monthlyRevenue,
        runway: analysis.runwayMonths,
        revenueGrowthRate: analysis.revenueGrowth,
        burnIncreasing: analysis.expenseGrowth > 0,
        revenueGrowthSlowing: analysis.revenueGrowth < 0.1,
        approachingBreakeven: analysis.monthlyRevenue >= analysis.monthlyBurn * 0.9,
      };

      const response = await performAnalysis(mode, context);
      setAnalysisResult(response);
      toast.success('Analysis Complete', { description: `${mode} analysis finished` });
    } catch (error) {
      toast.error('Analysis Failed', { description: error instanceof Error ? error.message : 'Unknown error' });
      setAnalysisResult(`Error: ${error instanceof Error ? error.message : 'Analysis failed'}`);
    } finally {
      setIsAnalysisRunning(false);
      setActiveAnalysisMode(null);
    }
  }, [isAnalysisRunning, analysis]);

  const handleDownloadReport = () => {
    try {
      const report = generateInvestorReport(analysis);
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `runway-dna-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast.success('Report Downloaded', {
        description: 'Investor report saved to your downloads.',
      });
    } catch (err) {
      toast.error('Download Failed', {
        description: err instanceof Error ? err.message : 'Could not generate report.',
      });
    }
  };

  const handleCopyReport = async () => {
    const report = generateInvestorReport(analysis);
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      toast.success('Copied to Clipboard', {
        description: 'Investor report ready to paste.',
      });
    } catch {
      // Fallback for older browsers
      try {
        const textArea = document.createElement('textarea');
        textArea.value = report;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        toast.success('Copied to Clipboard', {
          description: 'Investor report ready to paste.',
        });
      } catch (err) {
        toast.error('Copy Failed', {
          description: 'Could not copy to clipboard.',
        });
      }
    }
  };

  const isProcessing = progress?.stage && !['idle', 'complete', 'error'].includes(progress.stage);

  const runwayPercent = Math.min(100, (analysis.runwayMonths / 24) * 100);
  const netBurn = analysis.monthlyBurn - analysis.monthlyRevenue;

  return (
    <>
      {/* Confetti celebration for first snapshot */}
      <ConfettiComponent />

      <motion.div
        className="space-y-6"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <header className="flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold tracking-tight">
              <span className="gradient-text-mixed">DNA Lab</span>
            </h1>
            <p className="text-text-secondary mt-1">Decode your financial genome</p>
          </div>
          <div className="flex items-center gap-4">
            <AnimatePresence>
              {syncStatus !== 'idle' && (
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  className={cn(
                    'flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium',
                    syncStatus === 'syncing' && 'bg-cyan-electric/15 text-cyan-electric',
                    syncStatus === 'synced' && 'bg-success-muted text-success',
                    syncStatus === 'error' && 'bg-danger-muted text-danger'
                  )}
                >
                  {syncStatus === 'syncing' && <Loader2 className="w-4 h-4 animate-spin" />}
                  {syncStatus === 'synced' && <Check className="w-4 h-4" />}
                  {syncStatus === 'error' && <Database className="w-4 h-4" />}
                  {syncStatus === 'syncing' ? 'Syncing...' : syncStatus === 'synced' ? 'Saved to Archive' : 'Sync Failed'}
                </motion.div>
              )}
            </AnimatePresence>
            <div className="relative">
              <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-tertiary" />
              <input
                type="text"
                placeholder="Cash on hand"
                value={formatCurrency(cashInput)}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setCashInput(parseFloat(e.target.value.replace(/[$,]/g, '')) || 0)}
                className="w-44 bg-surface-1 border border-border rounded-xl pl-10 pr-4 py-2.5 text-text-primary text-sm focus:border-cyan-electric/50 focus:ring-1 focus:ring-cyan-electric/20 transition-all"
              />
            </div>
          </div>
        </header>

        <AnimatePresence>
          {progress?.stage === 'error' && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="glass-card p-4 border-danger/50 bg-danger/10"
            >
              <p className="text-danger">{progress.message}</p>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Smart Upload Section */}
        {!isProcessing && (
          <MotionCard
            variant="elevated"
            className="p-6"
            custom={-2}
            initial="hidden"
            animate="visible"
            variants={cardVariants}
          >
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="w-5 h-5 text-violet-vivid" />
              <h3 className="text-lg font-semibold text-white">Upload Financial Data</h3>
            </div>

            <SmartUpload
              onExtracted={handleAIExtracted}
              onError={(error) => toast.error('Extraction Error', { description: error })}
            />
          </MotionCard>
        )}

        {/* Quick Analysis Buttons */}
        {!isProcessing && (
          <MotionCard
            variant="elevated"
            className="p-4"
            custom={-1}
            initial="hidden"
            animate="visible"
            variants={cardVariants}
          >
            <h3 className="text-sm font-semibold mb-3 text-gray-300">Quick AI Analysis</h3>
            <div className="flex flex-wrap gap-2">
              {[
                {
                  mode: 'runway' as AnalysisType,
                  label: 'Runway Analysis',
                  icon: Plane,
                  iconColor: 'text-cyan-electric',
                  activeColor: 'bg-cyan-electric text-charcoal'
                },
                {
                  mode: 'fundraising' as AnalysisType,
                  label: 'Fundraising Readiness',
                  icon: Target,
                  iconColor: 'text-violet-vivid',
                  activeColor: 'bg-violet-vivid text-white'
                },
                {
                  mode: 'growth' as AnalysisType,
                  label: 'Growth Assessment',
                  icon: BarChart3,
                  iconColor: 'text-success',
                  activeColor: 'bg-success text-charcoal'
                },
                {
                  mode: 'risk' as AnalysisType,
                  label: 'Risk Analysis',
                  icon: AlertTriangle,
                  iconColor: 'text-warning',
                  activeColor: 'bg-warning text-charcoal'
                },
                {
                  mode: 'breakeven' as AnalysisType,
                  label: 'Path to Profitability',
                  icon: Heart,
                  iconColor: 'text-pink-400',
                  activeColor: 'bg-cyan-electric text-charcoal'
                }
              ].map(btn => {
                const IconComponent = btn.icon;
                const isActive = activeAnalysisMode === btn.mode;
                return (
                  <MotionButton
                    key={btn.mode}
                    onClick={() => runAnalysis(btn.mode)}
                    disabled={isAnalysisRunning}
                    variant="secondary"
                    className={`flex items-center gap-2 px-4 py-2 text-sm transition-all ${isActive
                      ? btn.activeColor
                      : isAnalysisRunning
                        ? 'opacity-50 cursor-not-allowed'
                        : 'hover:bg-white/10'
                      }`}
                  >
                    {isAnalysisRunning && isActive ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Running...
                      </>
                    ) : (
                      <>
                        <IconComponent className={`w-4 h-4 ${isActive ? '' : btn.iconColor}`} />
                        {btn.label}
                      </>
                    )}
                  </MotionButton>
                );
              })}
            </div>
            {analysisResult && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="mt-4 p-4 bg-white/5 rounded-lg border border-white/10"
              >
                <p className="text-sm text-gray-300 whitespace-pre-wrap">{analysisResult}</p>
              </motion.div>
            )}
          </MotionCard>
        )}

        {isProcessing ? (
          <SequencingLoader />
        ) : (
          <div className="grid grid-cols-12 gap-4">
            <MotionCard
              variant="elevated"
              className="col-span-8 p-6"
              custom={0}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-lg font-semibold">Financial Trajectory</h2>
                <div className="flex gap-4 text-sm">
                  <span className="flex items-center gap-2">
                    <span className="w-3 h-3 rounded-full bg-cyan-electric animate-glow-pulse" />
                    Revenue
                  </span>
                  <span className="flex items-center gap-2">
                    <span className="w-3 h-3 rounded-full bg-violet-vivid" />
                    Expenses
                  </span>
                </div>
              </div>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={analysis.revenueTrend}>
                    <defs>
                      {/* Enhanced Revenue Gradient */}
                      <linearGradient id="revenueGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#00D4FF" stopOpacity={0.5} />
                        <stop offset="50%" stopColor="#00D4FF" stopOpacity={0.2} />
                        <stop offset="100%" stopColor="#00D4FF" stopOpacity={0} />
                      </linearGradient>
                      {/* Enhanced Expense Gradient */}
                      <linearGradient id="expenseGrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#8B5CF6" stopOpacity={0.4} />
                        <stop offset="50%" stopColor="#8B5CF6" stopOpacity={0.15} />
                        <stop offset="100%" stopColor="#8B5CF6" stopOpacity={0} />
                      </linearGradient>
                      {/* Glow Filter - Cyan */}
                      <filter id="glowCyan" x="-50%" y="-50%" width="200%" height="200%">
                        <feGaussianBlur stdDeviation="4" result="coloredBlur" />
                        <feMerge>
                          <feMergeNode in="coloredBlur" />
                          <feMergeNode in="SourceGraphic" />
                        </feMerge>
                      </filter>
                      {/* Glow Filter - Violet */}
                      <filter id="glowViolet" x="-50%" y="-50%" width="200%" height="200%">
                        <feGaussianBlur stdDeviation="3" result="coloredBlur" />
                        <feMerge>
                          <feMergeNode in="coloredBlur" />
                          <feMergeNode in="SourceGraphic" />
                        </feMerge>
                      </filter>
                    </defs>
                    <XAxis dataKey="month" stroke="#555" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="#555" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(v) => `$${v / 1000}k`} />
                    <Tooltip content={<CustomTooltip />} cursor={{ stroke: 'rgba(255,255,255,0.1)', strokeWidth: 1 }} />
                    <Area
                      type="monotone"
                      dataKey="revenue"
                      stroke="#00D4FF"
                      fill="url(#revenueGrad)"
                      strokeWidth={3}
                      filter="url(#glowCyan)"
                      animationBegin={0}
                      animationDuration={1500}
                      animationEasing="ease-out"
                    />
                    <Area
                      type="monotone"
                      dataKey="expenses"
                      stroke="#8B5CF6"
                      fill="url(#expenseGrad)"
                      strokeWidth={2}
                      filter="url(#glowViolet)"
                      animationBegin={300}
                      animationDuration={1500}
                      animationEasing="ease-out"
                    />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </MotionCard>

            <div className="col-span-4 space-y-4">
              {/* Hero Grade Display */}
              <MotionCard
                className="p-8 text-center bg-surface-1"
                custom={1}
                initial="hidden"
                animate="visible"
                variants={cardVariants}
              >
                <div className="text-xs text-text-tertiary uppercase tracking-widest font-medium mb-4">Financial Health Grade</div>
                <motion.div
                  key={analysis.grade}
                  initial={{ scale: 0.8, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                  className="flex justify-center"
                >
                  <GradeBadge grade={analysis.grade as 'A' | 'B' | 'C' | 'D' | 'F'} size="xl" showLabel />
                </motion.div>
              </MotionCard>

              {/* Hero Runway Display */}
              <MotionCard
                className="p-6 bg-surface-1"
                custom={2}
                initial="hidden"
                animate="visible"
                variants={cardVariants}
              >
                <div className="text-center">
                  <div className="text-xs text-text-tertiary uppercase tracking-widest font-medium mb-2">Runway</div>
                  <motion.div
                    className="text-5xl font-bold text-text-primary tabular-nums"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                  >
                    {analysis.runwayMonths >= 999 ? '∞' : analysis.runwayMonths.toFixed(1)}
                    <span className="text-xl text-text-tertiary font-medium ml-1">
                      {analysis.runwayMonths >= 999 ? '' : 'months'}
                    </span>
                  </motion.div>
                </div>

                {/* Progress bar */}
                <div className="mt-4 h-2 bg-surface-2 rounded-full overflow-hidden">
                  <motion.div
                    className={cn(
                      "h-full rounded-full",
                      analysis.runwayMonths >= 18 ? "bg-gradient-to-r from-success to-success-light" :
                        analysis.runwayMonths >= 12 ? "bg-gradient-to-r from-cyan-electric to-cyan-glow" :
                          analysis.runwayMonths >= 6 ? "bg-gradient-to-r from-warning to-warning-light" :
                            "bg-gradient-to-r from-danger to-danger-light"
                    )}
                    initial={{ width: 0 }}
                    animate={{ width: `${runwayPercent}%` }}
                    transition={{ duration: 0.8, ease: 'easeOut' }}
                  />
                </div>
              </MotionCard>
            </div>

            <MotionCard
              className="col-span-4 p-6"
              custom={3}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-success/20 flex items-center justify-center">
                  <TrendingUp className="w-5 h-5 text-success" />
                </div>
                <div className="flex-1">
                  <div className="text-sm text-gray-400">Monthly Revenue</div>
                  <div className="text-2xl font-bold text-success">{formatCurrency(analysis.monthlyRevenue)}</div>
                </div>
                <span className="badge badge-success">
                  {analysis.revenueGrowth >= 0 ? '+' : ''}
                  {Math.round(analysis.revenueGrowth * 100)}%
                </span>
              </div>
            </MotionCard>

            <MotionCard
              className="col-span-4 p-6"
              custom={4}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-violet-vivid/20 flex items-center justify-center">
                  <TrendingDown className="w-5 h-5 text-violet-vivid" />
                </div>
                <div className="flex-1">
                  <div className="text-sm text-gray-400">Monthly Burn</div>
                  <div className="text-2xl font-bold text-violet-vivid">{formatCurrency(analysis.monthlyBurn)}</div>
                </div>
                <span className="badge badge-violet">
                  {analysis.expenseGrowth >= 0 ? '+' : ''}
                  {Math.round(analysis.expenseGrowth * 100)}%
                </span>
              </div>
            </MotionCard>

            <MotionCard
              className="col-span-4 p-6"
              custom={5}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-xl bg-cyan-electric/20 flex items-center justify-center">
                  <DollarSign className="w-5 h-5 text-cyan-electric" />
                </div>
                <div className="flex-1">
                  <div className="text-sm text-gray-400">Cash on Hand</div>
                  <div className="text-2xl font-bold text-cyan-electric">{formatCurrency(analysis.cashOnHand, true)}</div>
                </div>
              </div>
            </MotionCard>

            <MotionCard
              className="col-span-12 p-6"
              custom={6}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-start gap-4">
                <motion.div
                  className="w-12 h-12 rounded-xl bg-gradient-to-br from-cyan-electric to-violet-vivid flex items-center justify-center flex-shrink-0"
                  animate={{
                    boxShadow: [
                      '0 0 20px rgba(0, 212, 255, 0.3)',
                      '0 0 30px rgba(139, 92, 246, 0.4)',
                      '0 0 20px rgba(0, 212, 255, 0.3)',
                    ],
                  }}
                  transition={{ duration: 2, repeat: Infinity }}
                >
                  <Sparkles className="w-6 h-6 text-charcoal" />
                </motion.div>
                <div>
                  <h3 className="font-semibold mb-2">AI Insight</h3>
                  <p className="text-gray-400 leading-relaxed">{analysis.insight}</p>
                </div>
              </div>
            </MotionCard>

            <MotionCard
              className="col-span-6 p-6"
              custom={7}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">Export Report</h3>
              </div>
              <div className="space-y-3">
                <MotionButton
                  variant="secondary"
                  onClick={handleDownloadReport}
                  className="w-full text-left flex items-center gap-3"
                >
                  <Download className="w-5 h-5" />
                  Download Investor Report
                </MotionButton>
                <MotionButton
                  variant="secondary"
                  onClick={handleCopyReport}
                  className="w-full text-left flex items-center gap-3"
                >
                  {copied ? <CheckCheck className="w-5 h-5 text-success" /> : <Copy className="w-5 h-5" />}
                  {copied ? 'Copied to Clipboard!' : 'Copy Report to Clipboard'}
                </MotionButton>
              </div>
            </MotionCard>

            <MotionCard
              className="col-span-6 p-6"
              custom={8}
              initial="hidden"
              animate="visible"
              variants={cardVariants}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-semibold">Key Metrics</h3>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-sm text-gray-400">Profit Margin</div>
                  <div className={`text-xl font-bold ${analysis.profitMargin >= 0 ? 'text-success' : 'text-danger'}`}>
                    {analysis.profitMargin.toFixed(1)}%
                  </div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">Burn Multiple</div>
                  <div className="text-xl font-bold text-cyan-electric">
                    {analysis.burnMultiple > 10 ? '>10x' : `${analysis.burnMultiple.toFixed(1)}x`}
                  </div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">MRR Growth</div>
                  <div className="text-xl font-bold text-violet-vivid">{Math.round(analysis.revenueGrowth * 100)}%</div>
                </div>
                <div>
                  <div className="text-sm text-gray-400">Net Burn</div>
                  <div className={`text-xl font-bold ${netBurn > 0 ? 'text-warning' : 'text-success'}`}>
                    {netBurn > 0 ? '-' : '+'}
                    {formatCurrency(Math.abs(netBurn), true)}
                  </div>
                </div>
              </div>
            </MotionCard>
          </div>
        )}
      </motion.div>
    </>
  );
}
